export default {
  id: "cheaperinference",
  priority: 50,
  alias: "cheaperinference",
  display: {
    name: "Cheaper Inference",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "CI",
    website: "https://cheaperinference.com/?utm_source=omniroute",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.cheaperinference.com/v1/chat/completions",
    validateUrl: "https://api.cheaperinference.com/v1/models",
  },
  models: [
    { id: "aion-labs.aion-2-0", name: "Aion 2.0" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4-7-fast", name: "Claude Opus 4.7 Fast" },
    { id: "claude-opus-4-8-fast", name: "Claude Opus 4.8 Fast" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-5-fast", name: "Claude Opus 5 Fast" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "glm-4.5", name: "GLM-4.5" },
    { id: "glm-4.5-air", name: "GLM-4.5 Air" },
    { id: "glm-4.6", name: "GLM-4.6" },
    { id: "glm-4.7", name: "GLM-4.7" },
    { id: "glm-5", name: "GLM-5" },
    { id: "glm-5.1", name: "GLM-5.1" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "google/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
  ],
}
