export default {
  id: "conol-web",
  priority: 50,
  alias: "conol-web",
  display: {
    name: "Conol (Unofficial/Experimental)",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "CU",
    website: "https://conol.ai",
  },
  category: "webCookie",
  transport: {
    baseUrl: "https://conol.ai/api/sessions",
  },
  models: [
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-4-8", name: "Claude Opus 4 8" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4 6" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4 5" },
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.5-pro", name: "GPT 5.5 Pro" },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "deepseek/deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "openrouter/fusion", name: "Fusion" },
    { id: "z-ai/glm-5.2", name: "GLM 5.2" },
    { id: "tencent/hy3", name: "Hy3" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "qwen/qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "minimax/minimax-m3", name: "Minimax M3" },
    { id: "stepfun/step-3.7-flash", name: "Step 3.7 Flash" },
    { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "x-ai/grok-4.3", name: "Grok 4.3" },
    { id: "deepseek/deepseek-v4-flash", name: "Deepseek V4 Flash" },
    { id: "xiaomi/mimo-v2.5", name: "Mimo V2.5" },
    { id: "xiaomi/mimo-v2.5-pro", name: "Mimo V2.5 Pro" },
  ],
}
