export default {
  id: "cursor-api",
  priority: 50,
  alias: "cursor-api",
  display: {
    name: "Cursor API",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "CA",
    website: "https://cursor.com/dashboard/api",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api2.cursor.sh",
  },
  models: [
    { id: "auto", name: "Auto (current, default)" },
    { id: "auto-cost", name: "Auto (cost)" },
    { id: "auto-balance", name: "Auto (balance)" },
    { id: "auto-intelligence", name: "Auto (intelligence)" },
    { id: "cursor-grok-4.6-xhigh-fast", name: "Cursor Grok 4.6 Xhigh Fast" },
    { id: "cursor-grok-4.6-xhigh", name: "Cursor Grok 4.6 Xhigh" },
    { id: "cursor-grok-4.6-high-fast", name: "Cursor Grok 4.6 High Fast" },
    { id: "cursor-grok-4.6-high", name: "Cursor Grok 4.6 High" },
    { id: "cursor-grok-4.6-medium-fast", name: "Cursor Grok 4.6 Medium Fast" },
    { id: "cursor-grok-4.6-medium", name: "Cursor Grok 4.6 Medium" },
    { id: "cursor-grok-4.6-low-fast", name: "Cursor Grok 4.6 Low Fast" },
    { id: "cursor-grok-4.6-low", name: "Cursor Grok 4.6 Low" },
    { id: "composer-2.5-fast", name: "Composer 2.5 Fast" },
    { id: "composer-2.5", name: "Composer 2.5" },
    { id: "claude-fable-5-1-thinking-max-1m", name: "Claude Fable 5.1 1M Max Thinking" },
    { id: "claude-fable-5-1-thinking-max", name: "Claude Fable 5.1 Max Thinking" },
    { id: "claude-fable-5-1-thinking-xhigh-1m", name: "Claude Fable 5.1 1M Xhigh Thinking" },
    { id: "claude-fable-5-1-thinking-xhigh", name: "Claude Fable 5.1 Xhigh Thinking" },
    { id: "claude-fable-5-1-thinking-high-1m", name: "Claude Fable 5.1 1M High Thinking" },
    { id: "claude-fable-5-1-thinking-high", name: "Claude Fable 5.1 High Thinking" },
    { id: "claude-fable-5-1-thinking-medium-1m", name: "Claude Fable 5.1 1M Medium Thinking" },
    { id: "claude-fable-5-1-thinking-medium", name: "Claude Fable 5.1 Medium Thinking" },
    { id: "claude-fable-5-1-thinking-low-1m", name: "Claude Fable 5.1 1M Low Thinking" },
    { id: "claude-fable-5-1-thinking-low", name: "Claude Fable 5.1 Low Thinking" },
    { id: "claude-opus-5-thinking-max-fast-1m", name: "Claude Opus 5 1M Max Thinking Fast" },
    { id: "claude-opus-5-thinking-max-fast", name: "Claude Opus 5 Max Thinking Fast" },
    { id: "claude-opus-5-thinking-max-1m", name: "Claude Opus 5 1M Max Thinking" },
    { id: "claude-opus-5-thinking-max", name: "Claude Opus 5 Max Thinking" },
    { id: "claude-opus-5-thinking-xhigh-fast-1m", name: "Claude Opus 5 1M Xhigh Thinking Fast" },
    { id: "claude-opus-5-thinking-xhigh-fast", name: "Claude Opus 5 Xhigh Thinking Fast" },
    { id: "claude-opus-5-thinking-xhigh-1m", name: "Claude Opus 5 1M Xhigh Thinking" },
    { id: "claude-opus-5-thinking-xhigh", name: "Claude Opus 5 Xhigh Thinking" },
    { id: "claude-opus-5-thinking-high-fast-1m", name: "Claude Opus 5 1M High Thinking Fast" },
    { id: "claude-opus-5-thinking-high-fast", name: "Claude Opus 5 High Thinking Fast" },
    { id: "claude-opus-5-thinking-high-1m", name: "Claude Opus 5 1M High Thinking" },
    { id: "claude-opus-5-thinking-high", name: "Claude Opus 5 High Thinking" },
    { id: "claude-opus-5-high-fast-1m", name: "Claude Opus 5 1M High Fast" },
    { id: "claude-opus-5-high-fast", name: "Claude Opus 5 High Fast" },
    { id: "claude-opus-5-high-1m", name: "Claude Opus 5 1M High" },
    { id: "claude-opus-5-high", name: "Claude Opus 5 High" },
    { id: "claude-opus-5-thinking-medium-fast-1m", name: "Claude Opus 5 1M Medium Thinking Fast" },
    { id: "claude-opus-5-thinking-medium-fast", name: "Claude Opus 5 Medium Thinking Fast" },
    { id: "claude-opus-5-thinking-medium-1m", name: "Claude Opus 5 1M Medium Thinking" },
    { id: "claude-opus-5-thinking-medium", name: "Claude Opus 5 Medium Thinking" },
    { id: "claude-opus-5-medium-fast-1m", name: "Claude Opus 5 1M Medium Fast" },
    { id: "claude-opus-5-medium-fast", name: "Claude Opus 5 Medium Fast" },
    { id: "claude-opus-5-medium-1m", name: "Claude Opus 5 1M Medium" },
    { id: "claude-opus-5-medium", name: "Claude Opus 5 Medium" },
    { id: "claude-opus-5-thinking-low-fast-1m", name: "Claude Opus 5 1M Low Thinking Fast" },
    { id: "claude-opus-5-thinking-low-fast", name: "Claude Opus 5 Low Thinking Fast" },
    { id: "claude-opus-5-thinking-low-1m", name: "Claude Opus 5 1M Low Thinking" },
    { id: "claude-opus-5-thinking-low", name: "Claude Opus 5 Low Thinking" },
    { id: "claude-opus-5-low-fast-1m", name: "Claude Opus 5 1M Low Fast" },
    { id: "claude-opus-5-low-fast", name: "Claude Opus 5 Low Fast" },
    { id: "claude-opus-5-low-1m", name: "Claude Opus 5 1M Low" },
    { id: "claude-opus-5-low", name: "Claude Opus 5 Low" },
    { id: "claude-opus-4-8-thinking-max-fast-1m", name: "Claude Opus 4.8 1M Max Thinking Fast" },
    { id: "claude-opus-4-8-thinking-max-fast", name: "Claude Opus 4.8 Max Thinking Fast" },
    { id: "claude-opus-4-8-thinking-max-1m", name: "Claude Opus 4.8 1M Max Thinking" },
    { id: "claude-opus-4-8-thinking-max", name: "Claude Opus 4.8 Max Thinking" },
    { id: "claude-opus-4-8-max-fast-1m", name: "Claude Opus 4.8 1M Max Fast" },
    { id: "claude-opus-4-8-max-fast", name: "Claude Opus 4.8 Max Fast" },
    { id: "claude-opus-4-8-max-1m", name: "Claude Opus 4.8 1M Max" },
    { id: "claude-opus-4-8-max", name: "Claude Opus 4.8 Max" },
    { id: "claude-opus-4-8-thinking-xhigh-fast-1m", name: "Claude Opus 4.8 1M Xhigh Thinking Fast" },
    { id: "claude-opus-4-8-thinking-xhigh-fast", name: "Claude Opus 4.8 Xhigh Thinking Fast" },
    { id: "claude-opus-4-8-thinking-xhigh-1m", name: "Claude Opus 4.8 1M Xhigh Thinking" },
    { id: "claude-opus-4-8-thinking-xhigh", name: "Claude Opus 4.8 Xhigh Thinking" },
    { id: "claude-opus-4-8-xhigh-fast-1m", name: "Claude Opus 4.8 1M Xhigh Fast" },
    { id: "claude-opus-4-8-xhigh-fast", name: "Claude Opus 4.8 Xhigh Fast" },
    { id: "claude-opus-4-8-xhigh-1m", name: "Claude Opus 4.8 1M Xhigh" },
    { id: "claude-opus-4-8-xhigh", name: "Claude Opus 4.8 Xhigh" },
    { id: "claude-opus-4-8-thinking-high-fast-1m", name: "Claude Opus 4.8 1M High Thinking Fast" },
    { id: "claude-opus-4-8-thinking-high-fast", name: "Claude Opus 4.8 High Thinking Fast" },
    { id: "claude-opus-4-8-thinking-high-1m", name: "Claude Opus 4.8 1M High Thinking" },
    { id: "claude-opus-4-8-thinking-high", name: "Claude Opus 4.8 High Thinking" },
    { id: "claude-opus-4-8-high-fast-1m", name: "Claude Opus 4.8 1M High Fast" },
    { id: "claude-opus-4-8-high-fast", name: "Claude Opus 4.8 High Fast" },
    { id: "claude-opus-4-8-high-1m", name: "Claude Opus 4.8 1M High" },
    { id: "claude-opus-4-8-high", name: "Claude Opus 4.8 High" },
    { id: "claude-opus-4-8-thinking-medium-fast-1m", name: "Claude Opus 4.8 1M Medium Thinking Fast" },
    { id: "claude-opus-4-8-thinking-medium-fast", name: "Claude Opus 4.8 Medium Thinking Fast" },
    { id: "claude-opus-4-8-thinking-medium-1m", name: "Claude Opus 4.8 1M Medium Thinking" },
    { id: "claude-opus-4-8-thinking-medium", name: "Claude Opus 4.8 Medium Thinking" },
    { id: "claude-opus-4-8-medium-fast-1m", name: "Claude Opus 4.8 1M Medium Fast" },
    { id: "claude-opus-4-8-medium-fast", name: "Claude Opus 4.8 Medium Fast" },
    { id: "claude-opus-4-8-medium-1m", name: "Claude Opus 4.8 1M Medium" },
    { id: "claude-opus-4-8-medium", name: "Claude Opus 4.8 Medium" },
    { id: "claude-opus-4-8-thinking-low-fast-1m", name: "Claude Opus 4.8 1M Low Thinking Fast" },
    { id: "claude-opus-4-8-thinking-low-fast", name: "Claude Opus 4.8 Low Thinking Fast" },
    { id: "claude-opus-4-8-thinking-low-1m", name: "Claude Opus 4.8 1M Low Thinking" },
    { id: "claude-opus-4-8-thinking-low", name: "Claude Opus 4.8 Low Thinking" },
    { id: "claude-opus-4-8-low-fast-1m", name: "Claude Opus 4.8 1M Low Fast" },
    { id: "claude-opus-4-8-low-fast", name: "Claude Opus 4.8 Low Fast" },
    { id: "claude-opus-4-8-low-1m", name: "Claude Opus 4.8 1M Low" },
    { id: "claude-opus-4-8-low", name: "Claude Opus 4.8 Low" },
    { id: "claude-sonnet-5-thinking-max-1m", name: "Claude Sonnet 5 1M Max Thinking" },
    { id: "claude-sonnet-5-thinking-max", name: "Claude Sonnet 5 Max Thinking" },
    { id: "claude-sonnet-5-max-1m", name: "Claude Sonnet 5 1M Max" },
    { id: "claude-sonnet-5-max", name: "Claude Sonnet 5 Max" },
    { id: "claude-sonnet-5-thinking-xhigh-1m", name: "Claude Sonnet 5 1M Xhigh Thinking" },
    { id: "claude-sonnet-5-thinking-xhigh", name: "Claude Sonnet 5 Xhigh Thinking" },
    { id: "claude-sonnet-5-xhigh-1m", name: "Claude Sonnet 5 1M Xhigh" },
    { id: "claude-sonnet-5-xhigh", name: "Claude Sonnet 5 Xhigh" },
    { id: "claude-sonnet-5-thinking-high-1m", name: "Claude Sonnet 5 1M High Thinking" },
    { id: "claude-sonnet-5-thinking-high", name: "Claude Sonnet 5 High Thinking" },
    { id: "claude-sonnet-5-high-1m", name: "Claude Sonnet 5 1M High" },
    { id: "claude-sonnet-5-high", name: "Claude Sonnet 5 High" },
    { id: "claude-sonnet-5-thinking-medium-1m", name: "Claude Sonnet 5 1M Medium Thinking" },
    { id: "claude-sonnet-5-thinking-medium", name: "Claude Sonnet 5 Medium Thinking" },
    { id: "claude-sonnet-5-medium-1m", name: "Claude Sonnet 5 1M Medium" },
    { id: "claude-sonnet-5-medium", name: "Claude Sonnet 5 Medium" },
    { id: "claude-sonnet-5-thinking-low-1m", name: "Claude Sonnet 5 1M Low Thinking" },
    { id: "claude-sonnet-5-thinking-low", name: "Claude Sonnet 5 Low Thinking" },
    { id: "claude-sonnet-5-low-1m", name: "Claude Sonnet 5 1M Low" },
    { id: "claude-sonnet-5-low", name: "Claude Sonnet 5 Low" },
    { id: "claude-4.6-sonnet-max-thinking-1m", name: "Claude Sonnet 4.6 1M Max Thinking" },
    { id: "claude-4.6-sonnet-max-thinking", name: "Claude Sonnet 4.6 Max Thinking" },
    { id: "claude-4.6-sonnet-max-1m", name: "Claude Sonnet 4.6 1M Max" },
    { id: "claude-4.6-sonnet-max", name: "Claude Sonnet 4.6 Max" },
    { id: "claude-4.6-sonnet-high-thinking-1m", name: "Claude Sonnet 4.6 1M High Thinking" },
    { id: "claude-4.6-sonnet-high-thinking", name: "Claude Sonnet 4.6 High Thinking" },
    { id: "claude-4.6-sonnet-high-1m", name: "Claude Sonnet 4.6 1M High" },
    { id: "claude-4.6-sonnet-high", name: "Claude Sonnet 4.6 High" },
    { id: "claude-4.6-sonnet-medium-thinking-1m", name: "Claude Sonnet 4.6 1M Medium Thinking" },
    { id: "claude-4.6-sonnet-medium-thinking", name: "Claude Sonnet 4.6 Medium Thinking" },
    { id: "claude-4.6-sonnet-medium-1m", name: "Claude Sonnet 4.6 1M Medium" },
    { id: "claude-4.6-sonnet-medium", name: "Claude Sonnet 4.6 Medium" },
    { id: "claude-4.6-sonnet-low-thinking-1m", name: "Claude Sonnet 4.6 1M Low Thinking" },
    { id: "claude-4.6-sonnet-low-thinking", name: "Claude Sonnet 4.6 Low Thinking" },
    { id: "claude-4.6-sonnet-low-1m", name: "Claude Sonnet 4.6 1M Low" },
    { id: "claude-4.6-sonnet-low", name: "Claude Sonnet 4.6 Low" },
    { id: "claude-4.5-haiku-thinking", name: "Claude Haiku 4.5 Thinking" },
    { id: "claude-4.5-haiku", name: "Claude Haiku 4.5" },
    { id: "gpt-5.6-sol-max-fast", name: "GPT-5.6 Sol Max Fast" },
    { id: "gpt-5.6-sol-max-1m", name: "GPT-5.6 Sol 1M Max" },
    { id: "gpt-5.6-sol-max", name: "GPT-5.6 Sol Max" },
    { id: "gpt-5.6-sol-xhigh-fast", name: "GPT-5.6 Sol Xhigh Fast" },
    { id: "gpt-5.6-sol-xhigh-1m", name: "GPT-5.6 Sol 1M Xhigh" },
    { id: "gpt-5.6-sol-xhigh", name: "GPT-5.6 Sol Xhigh" },
    { id: "gpt-5.6-sol-high-fast", name: "GPT-5.6 Sol High Fast" },
    { id: "gpt-5.6-sol-high-1m", name: "GPT-5.6 Sol 1M High" },
    { id: "gpt-5.6-sol-high", name: "GPT-5.6 Sol High" },
    { id: "gpt-5.6-sol-medium-fast", name: "GPT-5.6 Sol Medium Fast" },
    { id: "gpt-5.6-sol-medium-1m", name: "GPT-5.6 Sol 1M Medium" },
    { id: "gpt-5.6-sol-medium", name: "GPT-5.6 Sol Medium" },
    { id: "gpt-5.6-sol-low-fast", name: "GPT-5.6 Sol Low Fast" },
    { id: "gpt-5.6-sol-low-1m", name: "GPT-5.6 Sol 1M Low" },
    { id: "gpt-5.6-sol-low", name: "GPT-5.6 Sol Low" },
    { id: "gpt-5.6-sol-none-fast", name: "GPT-5.6 Sol None Fast" },
    { id: "gpt-5.6-sol-none-1m", name: "GPT-5.6 Sol 1M None" },
    { id: "gpt-5.6-sol-none", name: "GPT-5.6 Sol None" },
    { id: "gpt-5.6-terra-max-fast", name: "GPT-5.6 Terra Max Fast" },
    { id: "gpt-5.6-terra-max-1m", name: "GPT-5.6 Terra 1M Max" },
    { id: "gpt-5.6-terra-max", name: "GPT-5.6 Terra Max" },
    { id: "gpt-5.6-terra-xhigh-fast", name: "GPT-5.6 Terra Xhigh Fast" },
    { id: "gpt-5.6-terra-xhigh-1m", name: "GPT-5.6 Terra 1M Xhigh" },
    { id: "gpt-5.6-terra-xhigh", name: "GPT-5.6 Terra Xhigh" },
    { id: "gpt-5.6-terra-high-fast", name: "GPT-5.6 Terra High Fast" },
    { id: "gpt-5.6-terra-high-1m", name: "GPT-5.6 Terra 1M High" },
    { id: "gpt-5.6-terra-high", name: "GPT-5.6 Terra High" },
    { id: "gpt-5.6-terra-medium-fast", name: "GPT-5.6 Terra Medium Fast" },
    { id: "gpt-5.6-terra-medium-1m", name: "GPT-5.6 Terra 1M Medium" },
    { id: "gpt-5.6-terra-medium", name: "GPT-5.6 Terra Medium" },
    { id: "gpt-5.6-terra-low-fast", name: "GPT-5.6 Terra Low Fast" },
    { id: "gpt-5.6-terra-low-1m", name: "GPT-5.6 Terra 1M Low" },
    { id: "gpt-5.6-terra-low", name: "GPT-5.6 Terra Low" },
    { id: "gpt-5.6-terra-none-fast", name: "GPT-5.6 Terra None Fast" },
    { id: "gpt-5.6-terra-none-1m", name: "GPT-5.6 Terra 1M None" },
    { id: "gpt-5.6-terra-none", name: "GPT-5.6 Terra None" },
    { id: "gpt-5.6-luna-max-fast", name: "GPT-5.6 Luna Max Fast" },
    { id: "gpt-5.6-luna-max-1m", name: "GPT-5.6 Luna 1M Max" },
    { id: "gpt-5.6-luna-max", name: "GPT-5.6 Luna Max" },
    { id: "gpt-5.6-luna-xhigh-fast", name: "GPT-5.6 Luna Xhigh Fast" },
    { id: "gpt-5.6-luna-xhigh-1m", name: "GPT-5.6 Luna 1M Xhigh" },
    { id: "gpt-5.6-luna-xhigh", name: "GPT-5.6 Luna Xhigh" },
    { id: "gpt-5.6-luna-high-fast", name: "GPT-5.6 Luna High Fast" },
    { id: "gpt-5.6-luna-high-1m", name: "GPT-5.6 Luna 1M High" },
    { id: "gpt-5.6-luna-high", name: "GPT-5.6 Luna High" },
    { id: "gpt-5.6-luna-medium-fast", name: "GPT-5.6 Luna Medium Fast" },
    { id: "gpt-5.6-luna-medium-1m", name: "GPT-5.6 Luna 1M Medium" },
    { id: "gpt-5.6-luna-medium", name: "GPT-5.6 Luna Medium" },
    { id: "gpt-5.6-luna-low-fast", name: "GPT-5.6 Luna Low Fast" },
    { id: "gpt-5.6-luna-low-1m", name: "GPT-5.6 Luna 1M Low" },
    { id: "gpt-5.6-luna-low", name: "GPT-5.6 Luna Low" },
    { id: "gpt-5.6-luna-none-fast", name: "GPT-5.6 Luna None Fast" },
    { id: "gpt-5.6-luna-none-1m", name: "GPT-5.6 Luna 1M None" },
    { id: "gpt-5.6-luna-none", name: "GPT-5.6 Luna None" },
    { id: "gemini-3.7-flash-high", name: "Gemini 3.7 Flash High" },
    { id: "gemini-3.7-flash-medium", name: "Gemini 3.7 Flash Medium" },
    { id: "gemini-3.7-flash-low", name: "Gemini 3.7 Flash Low" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "kimi-k3-max", name: "Kimi K3 Max" },
    { id: "kimi-k3-high", name: "Kimi K3 High" },
    { id: "kimi-k3-low", name: "Kimi K3 Low" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "glm-5.2-max", name: "GLM 5.2 Max" },
    { id: "glm-5.2-high", name: "GLM 5.2 High" },
  ],
}
