export default {
  id: "devin-desktop",
  priority: 50,
  alias: "devin-desktop",
  display: {
    name: "Devin Desktop",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "DD",
    website: "https://devin.ai",
  },
  category: "oauth",
  transport: {
    baseUrl: "https://server.codeium.com",
  },
  models: [
    { id: "claude-fable-5-1-max", name: "Claude Fable 5.1 Max" },
    { id: "claude-fable-5-1-xhigh", name: "Claude Fable 5.1 XHigh" },
    { id: "claude-fable-5-1-high", name: "Claude Fable 5.1 High" },
    { id: "claude-fable-5-1-medium", name: "Claude Fable 5.1 Medium" },
    { id: "claude-fable-5-1-low", name: "Claude Fable 5.1 Low" },
    { id: "claude-opus-5-max-fast", name: "Claude Opus 5 Max Fast" },
    { id: "claude-opus-5-max", name: "Claude Opus 5 Max" },
    { id: "claude-opus-5-xhigh-fast", name: "Claude Opus 5 XHigh Fast" },
    { id: "claude-opus-5-xhigh", name: "Claude Opus 5 XHigh" },
    { id: "claude-opus-5-high-fast", name: "Claude Opus 5 High Fast" },
    { id: "claude-opus-5-high", name: "Claude Opus 5 High" },
    { id: "claude-opus-5-medium-fast", name: "Claude Opus 5 Medium Fast" },
    { id: "claude-opus-5-medium", name: "Claude Opus 5 Medium" },
    { id: "claude-opus-5-low-fast", name: "Claude Opus 5 Low Fast" },
    { id: "claude-opus-5-low", name: "Claude Opus 5 Low" },
    { id: "claude-opus-4-8-max-fast", name: "Claude Opus 4.8 Max Fast" },
    { id: "claude-opus-4-8-max", name: "Claude Opus 4.8 Max" },
    { id: "claude-opus-4-8-xhigh-fast", name: "Claude Opus 4.8 XHigh Fast" },
    { id: "claude-opus-4-8-xhigh", name: "Claude Opus 4.8 XHigh" },
    { id: "claude-opus-4-8-high-fast", name: "Claude Opus 4.8 High Fast" },
    { id: "claude-opus-4-8-high", name: "Claude Opus 4.8 High" },
    { id: "claude-opus-4-8-medium-fast", name: "Claude Opus 4.8 Medium Fast" },
    { id: "claude-opus-4-8-medium", name: "Claude Opus 4.8 Medium" },
    { id: "claude-opus-4-8-low-fast", name: "Claude Opus 4.8 Low Fast" },
    { id: "claude-opus-4-8-low", name: "Claude Opus 4.8 Low" },
    { id: "claude-sonnet-5-max", name: "Claude Sonnet 5 Max" },
    { id: "claude-sonnet-5-xhigh", name: "Claude Sonnet 5 XHigh" },
    { id: "claude-sonnet-5-high", name: "Claude Sonnet 5 High" },
    { id: "claude-sonnet-5-medium", name: "Claude Sonnet 5 Medium" },
    { id: "claude-sonnet-5-low", name: "Claude Sonnet 5 Low" },
    { id: "claude-sonnet-4-6-thinking-1m", name: "Claude Sonnet 4.6 Thinking 1M" },
    { id: "claude-sonnet-4-6-1m", name: "Claude Sonnet 4.6 1M" },
    { id: "claude-sonnet-4-6-thinking", name: "Claude Sonnet 4.6 Thinking" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "MODEL_PRIVATE_11", name: "Claude Haiku 4.5" },
    { id: "gpt-5-6-sol-max-priority", name: "GPT-5.6 Sol Max Thinking Fast" },
    { id: "gpt-5-6-sol-max", name: "GPT-5.6 Sol Max Thinking" },
    { id: "gpt-5-6-sol-xhigh-priority", name: "GPT-5.6 Sol XHigh Thinking Fast" },
    { id: "gpt-5-6-sol-xhigh", name: "GPT-5.6 Sol XHigh Thinking" },
    { id: "gpt-5-6-sol-high-priority", name: "GPT-5.6 Sol High Thinking Fast" },
    { id: "gpt-5-6-sol-high", name: "GPT-5.6 Sol High Thinking" },
    { id: "gpt-5-6-sol-medium-priority", name: "GPT-5.6 Sol Medium Thinking Fast" },
    { id: "gpt-5-6-sol-medium", name: "GPT-5.6 Sol Medium Thinking" },
    { id: "gpt-5-6-sol-low-priority", name: "GPT-5.6 Sol Low Thinking Fast" },
    { id: "gpt-5-6-sol-low", name: "GPT-5.6 Sol Low Thinking" },
    { id: "gpt-5-6-sol-none-priority", name: "GPT-5.6 Sol No Thinking Fast" },
    { id: "gpt-5-6-sol-none", name: "GPT-5.6 Sol No Thinking" },
    { id: "gpt-5-6-terra-max-priority", name: "GPT-5.6 Terra Max Thinking Fast" },
    { id: "gpt-5-6-terra-max", name: "GPT-5.6 Terra Max Thinking" },
    { id: "gpt-5-6-terra-xhigh-priority", name: "GPT-5.6 Terra XHigh Thinking Fast" },
    { id: "gpt-5-6-terra-xhigh", name: "GPT-5.6 Terra XHigh Thinking" },
    { id: "gpt-5-6-terra-high-priority", name: "GPT-5.6 Terra High Thinking Fast" },
    { id: "gpt-5-6-terra-high", name: "GPT-5.6 Terra High Thinking" },
    { id: "gpt-5-6-terra-medium-priority", name: "GPT-5.6 Terra Medium Thinking Fast" },
    { id: "gpt-5-6-terra-medium", name: "GPT-5.6 Terra Medium Thinking" },
    { id: "gpt-5-6-terra-low-priority", name: "GPT-5.6 Terra Low Thinking Fast" },
    { id: "gpt-5-6-terra-low", name: "GPT-5.6 Terra Low Thinking" },
    { id: "gpt-5-6-terra-none-priority", name: "GPT-5.6 Terra No Thinking Fast" },
    { id: "gpt-5-6-terra-none", name: "GPT-5.6 Terra No Thinking" },
    { id: "gpt-5-6-luna-max-priority", name: "GPT-5.6 Luna Max Thinking Fast" },
    { id: "gpt-5-6-luna-max", name: "GPT-5.6 Luna Max Thinking" },
    { id: "gpt-5-6-luna-xhigh-priority", name: "GPT-5.6 Luna XHigh Thinking Fast" },
    { id: "gpt-5-6-luna-xhigh", name: "GPT-5.6 Luna XHigh Thinking" },
    { id: "gpt-5-6-luna-high-priority", name: "GPT-5.6 Luna High Thinking Fast" },
    { id: "gpt-5-6-luna-high", name: "GPT-5.6 Luna High Thinking" },
    { id: "gpt-5-6-luna-medium-priority", name: "GPT-5.6 Luna Medium Thinking Fast" },
    { id: "gpt-5-6-luna-medium", name: "GPT-5.6 Luna Medium Thinking" },
    { id: "gpt-5-6-luna-low-priority", name: "GPT-5.6 Luna Low Thinking Fast" },
    { id: "gpt-5-6-luna-low", name: "GPT-5.6 Luna Low Thinking" },
    { id: "gpt-5-6-luna-none-priority", name: "GPT-5.6 Luna No Thinking Fast" },
    { id: "gpt-5-6-luna-none", name: "GPT-5.6 Luna No Thinking" },
    { id: "kimi-k3-max", name: "Kimi K3 Max" },
    { id: "kimi-k3-high", name: "Kimi K3 High" },
    { id: "kimi-k3-low", name: "Kimi K3 Low" },
    { id: "kimi-k2-7", name: "Kimi K2.7" },
    { id: "glm-5-3-max", name: "GLM-5.3 Max" },
    { id: "glm-5-3-high", name: "GLM-5.3 High" },
    { id: "glm-5-3-low", name: "GLM-5.3 Low" },
    { id: "glm-5-3-flash-max", name: "GLM-5.3 Flash Max" },
    { id: "glm-5-3-flash-high", name: "GLM-5.3 Flash High" },
    { id: "glm-5-3-flash-low", name: "GLM-5.3 Flash Low" },
    { id: "swe-1-7", name: "SWE-1.7 Max" },
    { id: "swe-1-7-medium", name: "SWE-1.7 Medium" },
    { id: "swe-1-7-lightning", name: "SWE-1.7 Lightning Max" },
    { id: "swe-1-7-lightning-medium", name: "SWE-1.7 Lightning Medium" },
    { id: "adaptive", name: "Adaptive" },
    { id: "grok-4-6-xhigh", name: "Grok 4.6 XHigh" },
    { id: "grok-4-6-high", name: "Grok 4.6 High" },
    { id: "grok-4-6-medium", name: "Grok 4.6 Medium" },
    { id: "grok-4-6-low", name: "Grok 4.6 Low" },
    { id: "inkling-max", name: "Inkling Max" },
    { id: "inkling-xhigh", name: "Inkling X-High" },
    { id: "inkling-high", name: "Inkling High" },
    { id: "inkling-medium", name: "Inkling Medium" },
    { id: "inkling-low", name: "Inkling Low" },
    { id: "inkling-none", name: "Inkling None" },
    { id: "deepseek-v4-flash-max", name: "DeepSeek V4 Flash Max" },
    { id: "deepseek-v4-flash-high", name: "DeepSeek V4 Flash High" },
    { id: "deepseek-v4-flash-low", name: "DeepSeek V4 Flash Low" },
    { id: "nemotron-3-ultra-high", name: "Nemotron 3 Ultra High" },
    { id: "nemotron-3-ultra-medium", name: "Nemotron 3 Ultra Medium" },
    { id: "nemotron-3-ultra-none", name: "Nemotron 3 Ultra None" },
    { id: "gemini-3-7-flash-high", name: "Gemini 3.7 Flash High" },
    { id: "gemini-3-7-flash-medium", name: "Gemini 3.7 Flash Medium" },
    { id: "gemini-3-7-flash-low", name: "Gemini 3.7 Flash Low" },
    { id: "gemini-3-1-pro-high", name: "Gemini 3.1 Pro High Thinking" },
    { id: "gemini-3-1-pro-low", name: "Gemini 3.1 Pro Low Thinking" },
    { id: "deepseek-v4-pro-max", name: "DeepSeek V4 Pro Max" },
    { id: "deepseek-v4-pro-high", name: "DeepSeek V4 Pro High" },
    { id: "deepseek-v4-pro-low", name: "DeepSeek V4 Pro Low" },
  ],
}
