export default {
  id: "glmt",
  priority: 50,
  alias: "glmt",
  display: {
    name: "GLM Thinking",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "GT",
    website: "https://open.bigmodel.cn",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.z.ai/api/coding/paas/v4/chat/completions",
    validateUrl: "https://api.z.ai/api/coding/paas/v4/models",
  },
  models: [
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "glm-5.3", name: "GLM 5.3" },
    { id: "glm-5.3-high", name: "GLM 5.3 High" },
    { id: "glm-5.3-low", name: "GLM 5.3 Low" },
    { id: "glm-5.3-max", name: "GLM 5.3 Max" },
    { id: "glm-5.3-flash-high", name: "GLM 5.3 Flash High" },
    { id: "glm-5.3-flash-low", name: "GLM 5.3 Flash Low" },
    { id: "glm-5.3-flash-max", name: "GLM 5.3 Flash Max" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.2-high", name: "GLM 5.2 High" },
    { id: "glm-5.2-max", name: "GLM 5.2 Max" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-5-turbo", name: "GLM 5 Turbo" },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "glm-4.6v", name: "GLM 4.6V (Vision)" },
    { id: "glm-4.6", name: "GLM 4.6" },
    { id: "glm-4.5v", name: "GLM 4.5V (Vision)" },
    { id: "glm-4.5", name: "GLM 4.5" },
    { id: "glm-4.5-air", name: "GLM 4.5 Air" },
  ],
}
