export default {
  id: "lmarena",
  priority: 50,
  hasFree: true,
  alias: "lmarena",
  display: {
    name: "Arena (Free)",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "AF",
    website: "https://arena.ai",
  },
  category: "webCookie",
  transport: {
    baseUrl: "https://arena.ai/nextjs-api/stream/create-evaluation",
  },
  models: [
    { id: "amazon.nova-pro-v1:0", name: "amazon.nova-pro-v1:0" },
    { id: "claude-haiku-4-5-20251001", name: "claude-haiku-4-5-20251001" },
    { id: "claude-sonnet-5", name: "claude-sonnet-5-high" },
    { id: "deepseek-v4-pro-thinking", name: "deepseek-v4-pro-thinking" },
    { id: "dola-seed-2.0-preview-vision", name: "dola-seed-2.0-preview-vision" },
    { id: "ernie-5.0-preview-1220", name: "ernie-5.0-preview-1220" },
    { id: "gemini-3.1-flash-lite", name: "gemini-3.1-flash-lite" },
    { id: "gemini-3.1-pro-preview", name: "gemini-3.1-pro-preview" },
    { id: "gemini-3.6-flash", name: "gemini-3.6-flash" },
    { id: "significant-otter", name: "gemma-4-26b-a4b" },
    { id: "pteronura", name: "gemma-4-31b" },
    { id: "glm-5.1", name: "glm-5.2 (max)" },
    { id: "glm-5v-turbo", name: "glm-5v-turbo" },
    { id: "gpt-oss-120b", name: "gpt-oss-120b" },
    { id: "gpt-5.2-high", name: "gpt-5.2-high" },
    { id: "gpt-5.4-mini-high", name: "gpt-5.4-mini-high" },
    { id: "gpt-5.4-nano-high", name: "gpt-5.4-nano-high" },
    { id: "gpt-5.5-instant", name: "gpt-5.5-instant" },
    { id: "grok-4.3/text", name: "grok-4.5" },
    { id: "hunyuan-vision-1.5-thinking", name: "hunyuan-vision-1.5-thinking" },
    { id: "hy3", name: "hy3" },
    { id: "kimi-k2.6", name: "kimi-k2.6" },
    { id: "ling-2.5-1t", name: "ling-2.5-1t" },
    { id: "longcat-2.0", name: "longcat-2.0" },
    { id: "mercury-2", name: "mercury-2" },
    { id: "mimo-v2.5", name: "mimo-v2.5" },
    { id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" },
    { id: "minimax-m3", name: "minimax-m3" },
    { id: "mistral-large-3", name: "mistral-large-3" },
    { id: "mistral-medium-3.5", name: "mistral-medium-3.5" },
    { id: "mistral-small-2603", name: "mistral-small-2603" },
    { id: "nova-2-lite", name: "nova-2-lite" },
    { id: "nvidia-nemotron-3-nano-30b-a3b-bf16", name: "nvidia-nemotron-3-nano-30b-a3b-bf16" },
    { id: "march26-chatbot1-public", name: "nvidia-nemotron-3-super-120b-a12b" },
    { id: "may26-chatbot4-public", name: "nvidia-nemotron-3-ultra-550b-a55b-nvfp4" },
    { id: "o3-2025-04-16", name: "o3-2025-04-16" },
    { id: "qwen3.5-397b-a17b", name: "qwen3.5-397b-a17b" },
    { id: "qwen3.7-max", name: "qwen3.7-max" },
    { id: "qwen3.7-plus", name: "qwen3.7-plus" },
    { id: "ring-2.5-1t", name: "ring-2.5-1t" },
    { id: "step-3.5-flash", name: "step-3.5-flash" },
    { id: "trinity-large-thinking", name: "trinity-large-thinking" },
    { id: "claude-sonnet-5-search", name: "claude-sonnet-5-search" },
    { id: "gemini-2.5-pro-grounding", name: "gemini-2.5-pro-grounding" },
    { id: "gemini-3-flash-grounding", name: "gemini-3-flash-grounding" },
    { id: "gpt-5.2-search", name: "gpt-5.2-search" },
    { id: "grok-4.3/search", name: "grok-4.3" },
    { id: "o3-search", name: "o3-search" },
  ],
}
