export default {
  id: "novita",
  priority: 50,
  hasFree: true,
  alias: "novita",
  display: {
    name: "Novita AI",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "NA",
    website: "https://novita.ai",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.novita.ai/openai/v1/chat/completions",
    validateUrl: "https://api.novita.ai/openai/v1/models",
  },
  models: [
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek/deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "zai-org/glm-5.2", name: "GLM 5.2" },
    { id: "zai-org/glm-5.1", name: "GLM 5.1" },
    { id: "zai-org/glm-4.7", name: "GLM 4.7" },
    { id: "minimax/minimax-m3", name: "MiniMax M3" },
    { id: "minimax/minimax-m2.7", name: "MiniMax M2.7" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen/qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen/qwen3.5-397b-a17b", name: "Qwen3.5 397B A17B" },
    { id: "qwen/qwen3-coder-480b-a35b-instruct", name: "Qwen3 Coder 480B" },
    { id: "xiaomimimo/mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "openai/gpt-oss-120b", name: "OpenAI gpt-oss-120b" },
    { id: "google/gemma-4-31b-it", name: "Gemma 4 31B" },
    { id: "meta-llama/llama-3.1-8b-instruct", name: "Llama 3.1 8B Instruct" },
  ],
}
