export default {
  id: "promptql",
  priority: 50,
  alias: "promptql",
  display: {
    name: "PromptQL (Unofficial/Experimental)",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "PU",
    website: "https://prompt.ql.app",
  },
  category: "webCookie",
  transport: {
    baseUrl: "https://data.prompt.ql.app/promptql/playground-v2-hge/v1/graphql",
  },
  models: [
    { id: "bedrock-claude-fable-5", name: "Claude Fable 5" },
    { id: "bedrock-claude-opus-5", name: "Claude Opus 5" },
    { id: "bedrock-claude-sonnet-4-5", name: "Claude Sonnet 4.5" },
    { id: "deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 0813" },
    { id: "deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "xai-grok-4-6", name: "Grok 4.6" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "minimax-m3", name: "Minimax M3" },
  ],
}
