export default {
  id: "uc-direct",
  priority: 50,
  alias: "uc-direct",
  display: {
    name: "UC Direct (uncensored.com)",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "UD",
    website: "https://uncensored.com",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.uncensored.com/api/v1",
    validateUrl: "https://api.uncensored.com/api/v1/models",
  },
  models: [
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-5-fast", name: "Claude Opus 5 Fast" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "gpt-4o", name: "GPT 4o" },
    { id: "gpt-4o-mini", name: "GPT 4o Mini" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5.2-codex", name: "GPT 5.2 Codex" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini" },
    { id: "gpt-5.4-pro", name: "GPT 5.4 Pro" },
    { id: "gpt-5.4-nano", name: "GPT 5.4 Nano" },
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.5-pro", name: "GPT 5.5 Pro" },
    { id: "gpt-5-mini", name: "GPT 5 Mini" },
    { id: "gpt-5-nano", name: "GPT 5 Nano" },
    { id: "openai-gpt-oss-120b", name: "GPT OSS 120b" },
    { id: "gemini-3-6-flash", name: "Gemini 3 6 Flash" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemma-3-27b-it", name: "Gemma 3 27b IT" },
    { id: "grok-4-6", name: "Grok 4 6" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "grok-4.20-beta", name: "Grok 4.20 Beta" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "deepseek-v4-flash-0731", name: "Deepseek V4 Flash 0731" },
    { id: "deepseek-v3.2", name: "Deepseek V3.2" },
    { id: "deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "deepseek-v4-flash", name: "Deepseek V4 Flash" },
    { id: "deepseek-r1", name: "Deepseek R1" },
    { id: "qwen-3-8-2-4t-a95b", name: "Qwen 3 8 2 4t A95b" },
    { id: "qwen-3-8-max", name: "Qwen 3 8 Max" },
    { id: "qwen-3-6-35b-a3b", name: "Qwen 3 6 35b A3B" },
    { id: "qwen3-235b-a22b-2507", name: "Qwen3 235b A22b 2507" },
    { id: "qwen3-235b-a22b-thinking-2507", name: "Qwen3 235b A22b Thinking 2507" },
    { id: "qwen3.5-397b-a17b", name: "Qwen3.5 397b A17b" },
    { id: "qwen3.6-27b", name: "Qwen3.6 27b" },
    { id: "qwen3-30b-a3b", name: "Qwen3 30b A3B" },
    { id: "qwen3-5-35b-a3b", name: "Qwen3 5 35b A3B" },
    { id: "qwen3-5-9b", name: "Qwen3 5 9b" },
    { id: "qwen3-coder", name: "Qwen3 Coder" },
    { id: "qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80b A3B Instruct" },
    { id: "qwen3-vl-235b-a22b-thinking", name: "Qwen3 VL 235b A22b Thinking" },
    { id: "qwen3-vl-30b-a3b-thinking", name: "Qwen3 VL 30b A3B Thinking" },
    { id: "qwen3.5-flash", name: "Qwen3.5 Flash" },
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2", name: "Kimi K2" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "glm-4.6", name: "GLM 4.6" },
    { id: "minimax-m2.1", name: "MiniMax M2.1" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "mistral-large", name: "Mistral Large" },
    { id: "mistral-small-3.2-24b-instruct", name: "Mistral Small 3.2 24b Instruct" },
    { id: "llama-3.2-3b-instruct", name: "Llama 3.2 3b Instruct" },
    { id: "llama-3.3-70b-instruct", name: "Llama 3.3 70b Instruct" },
    { id: "nvidia-nemotron-3-5-lightning-30b-a3b", name: "Nvidia Nemotron 3 5 Lightning 30b A3B" },
    { id: "nvidia-nemotron-3-nano-30b-a3b", name: "Nvidia Nemotron 3 Nano 30b A3B" },
    { id: "hermes-3-llama-3.1-405b", name: "Hermes 3 Llama 3.1 405b" },
    { id: "aion-labs.aion-2-0", name: "Aion 2 0" },
    { id: "inkling", name: "Inkling" },
  ],
}
