export default {
  id: "uc",
  priority: 50,
  alias: "uc",
  display: {
    name: "UC (uncensored.com)",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "UU",
    website: "https://uncensored.com",
  },
  category: "webCookie",
  transport: {
    baseUrl: "https://internal-6.pubyar.com",
  },
  models: [
    { id: "claude-opus-45", name: "Claude Opus 4.5" },
    { id: "claude-opus-46", name: "Claude Opus 4.6" },
    { id: "claude-opus-46-v2", name: "Claude Opus 4.6 (v2)" },
    { id: "claude-opus-47", name: "Claude Opus 4.7" },
    { id: "claude-opus-47-v2", name: "Claude Opus 4.7 (v2)" },
    { id: "claude-opus-48-uncensored", name: "Claude Opus 4.8 (Uncensored)" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "gemini-31-uncensored", name: "Gemini 3.1 (Uncensored)" },
    { id: "gemini-emotional", name: "Gemini (Emotional)" },
    { id: "gemini-3-uncensored", name: "Gemini 3 (Uncensored)" },
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-20", name: "Grok 4.20" },
    { id: "grok-4-3", name: "Grok 4.3" },
    { id: "kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "minimax-m2-her", name: "MiniMax M2 (Her)" },
  ],
}
