export default {
  id: "xkiro",
  priority: 50,
  hasFree: true,
  alias: "xkiro",
  display: {
    name: "xKiro",
    icon: "cloud",
    color: "#6B7280",
    textIcon: "XK",
    website: "https://xkiro.com",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.xkiro.com/v1/chat/completions",
    validateUrl: "https://api.xkiro.com/v1/models",
  },
  models: [
    { id: "qwen/qwen3-vl-plus:free", name: "Qwen3 VL Plus" },
    { id: "sensenova/sensenova-6.8-flash-lite", name: "SenseNova 6.8 Flash-Lite" },
    { id: "minimax/minimax-m2.7:free", name: "MiniMax M2.7" },
    { id: "minimax/minimax-m2.7-highspeed:free", name: "MiniMax M2.7 Highspeed" },
    { id: "minimax/minimax-m2.5:free", name: "MiniMax M2.5" },
    { id: "minimax/minimax-m3:free", name: "MiniMax M3" },
    { id: "minimax/minimax-m2.1-highspeed:free", name: "MiniMax M2.1 Highspeed" },
    { id: "minimax/minimax-m2.5-highspeed:free", name: "MiniMax M2.5 Highspeed" },
    { id: "minimax/minimax-m2.1:free", name: "MiniMax M2.1" },
    { id: "minimax/minimax-m2:free", name: "MiniMax M2" },
    { id: "qwen/qwen3.5-flash:free", name: "Qwen3.5 Flash" },
    { id: "qwen/qwen3.6-plus:free", name: "Qwen3.6 Plus" },
    { id: "qwen/qwen3.5-397b-a17b:free", name: "Qwen3.5 397B A17B" },
    { id: "qwen/qwen3.5-omni-flash:free", name: "Qwen3.5 Omni Flash" },
    { id: "mistralai/mistral-large-2512", name: "Mistral Large 3" },
    { id: "mistralai/mistral-medium-3.5", name: "Mistral Medium 3.5" },
    { id: "mistralai/mistral-small-2603", name: "Mistral Small 4" },
    { id: "mistralai/codestral-2508", name: "Codestral" },
    { id: "mistralai/devstral-medium", name: "Devstral 2" },
    { id: "mistralai/ministral-8b", name: "Ministral 3 8B" },
    { id: "mistralai/ministral-3b", name: "Ministral 3 3B" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "deepseek/deepseek-chat-v3.1", name: "DeepSeek V3.1" },
    { id: "qwen/qwen3.7-plus:free", name: "Qwen3.7 Plus" },
    { id: "mistralai/ministral-14b", name: "Ministral 3 14B" },
    { id: "qwen/qwen3.6-max-preview:free", name: "Qwen3.6 Max Preview" },
    { id: "qwen/qwen3.5-plus:free", name: "Qwen3.5 Plus" },
    { id: "qwen/qwen3.5-omni-plus:free", name: "Qwen3.5 Omni Plus" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "sensenova/sensenova-6.7-flash-lite", name: "SenseNova 6.7 Flash-Lite" },
    { id: "qwen/qwen3.8-max:free", name: "Qwen3.8 Max" },
    { id: "qwen/qwen3.7-max:free", name: "Qwen3.7 Max" },
    { id: "qwen/qwen3.6-27b:free", name: "Qwen3.6 27B" },
    { id: "qwen/qwen3.6-35b-a3b:free", name: "Qwen3.6 35B A3B" },
    { id: "qwen/qwen3-max:free", name: "Qwen3 Max" },
    { id: "qwen/qwen3-coder-plus:free", name: "Qwen3 Coder Plus" },
    { id: "qwen/qwen-plus-2025-07-28:free", name: "Qwen Plus 0728" },
    { id: "qwen/qwen3-omni-flash:free", name: "Qwen3 Omni Flash" },
  ],
}
